### ISSUE TITLE
GetChildrenAsync   Children are Null

### ISSUE THREAD

**Issue by XuJin186** [maliming/Owl.GeneralTree#1]
The entity Children property returned by the GetChildrenAsync method is null, and the calling code is:
`await _repository.GetChildrenAsync(null);`
But after trying to call the GetListAsync method of the Repository before the GetChildrenAsync method to query all the entities, the children of the entity are valuable, and all the calling codes:
` await _repository.GetListAsync();
            var qqqq = await _repository.GetChildrenAsync(null);`

**Comment by maliming** [comment]
Can it be reproduced by unit testing?
Please provide the code for the test method
